name: Run Tasks with API Key

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run the Python script
        env:
          AIPROXY_TOKEN: ${{ secrets.AIPROXY_TOKEN }}  # Access GitHub secret
        run: |
          python tasks.py
